# Project Name
TARGET = TimeLord

# Sources

COMMON_DIR = $(CURDIR)/../Common
C_INCLUDES += -I$(COMMON_DIR)
CPP_SOURCES += \
	$(COMMON_DIR)/TimeLord.cpp

CPP_SOURCES += \
    Main.cpp \
    PageOverview.cpp 

BASE_DIR = $(CURDIR)/../../../Base
include $(BASE_DIR)/MakefilePatch
